quarkus.datasource.db-kind=h2
quarkus.datasource.username=sa
quarkus.datasource.jdbc.url=jdbc:h2:/data/identity
%dev.quarkus.datasource.jdbc.url=jdbc:h2:./identity
%test.quarkus.datasource.jdbc.url=jdbc:h2:mem:test
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.hibernate-orm.dialect=org.hibernate.dialect.H2Dialect
quarkus.hibernate-orm.database.generation=update
%test.quarkus.hibernate-orm.database.generation=drop-and-create

smallrye.jwt.new.token.signature-algorithm=RS256
smallrye.jwt.sign.key.location=privateKey.pem
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=budget-management
mp.jwt.verify.token.age=900

quarkus.smallrye-openapi.security-scheme-name=JWT

feature.condition-simulation.enabled=true
