DELETE FROM USERS;

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD) VALUES (1, 'testuser', 'test@example.com', '$2a$12$82dbSr/XoRIHUx8LTMcg6eKwPK.7ZOfzS54pIuKDYQCpAyeMU8zka');
ALTER SEQUENCE user_seq RESTART WITH 2;
