DELETE FROM PIGGY_BANK_ALLOCATIONS;
DELETE FROM INVITATIONS;
DELETE FROM PIGGY_BANKS;
DELETE FROM USER_GROUPS;
DELETE FROM GROUPS;
DELETE FROM SAVINGS_OPERATIONS;
DELETE FROM SAVINGS;
DELETE FROM USERS;

INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD) VALUES (1, 'testuser', 'test@example.com', '$2a$12$82dbSr/XoRIHUx8LTMcg6eKwPK.7ZOfzS54pIuKDYQCpAyeMU8zka');
INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD) VALUES (2, 'testuser2', 'test2@example.com', '$2a$12$82dbSr/XoRIHUx8LTMcg6eKwPK.7ZOfzS54pIuKDYQCpAyeMU8zka');
INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD) VALUES (3, 'testuser3', 'test3@example.com', '$2a$12$82dbSr/XoRIHUx8LTMcg6eKwPK.7ZOfzS54pIuKDYQCpAyeMU8zka');
INSERT INTO USERS (ID, USERNAME, EMAIL, PASSWORD) VALUES (4, 'testuser4', 'test4@example.com', '$2a$12$82dbSr/XoRIHUx8LTMcg6eKwPK.7ZOfzS54pIuKDYQCpAyeMU8zka');
ALTER SEQUENCE user_seq RESTART WITH 5;

INSERT INTO SAVINGS (ID, USER_ID) VALUES (1, 1);
ALTER SEQUENCE savings_seq RESTART WITH 2;

INSERT INTO GROUPS (ID, NAME, ADMIN_ID) VALUES (1, 'testgroup', 1);
ALTER SEQUENCE group_seq RESTART WITH 3;

INSERT INTO USER_GROUPS (USER_ID, GROUP_ID) VALUES (1, 1);
INSERT INTO USER_GROUPS (USER_ID, GROUP_ID) VALUES (3, 1);

INSERT INTO PIGGY_BANKS (ID, NAME, TARGET_AMOUNT, CATEGORY, USER_ID, GROUP_ID, TYPE) VALUES (1, 'testpersonalpiggy', 1000.00, 'ENTERTAINMENT', 1, NULL, 'PERSONAL');
INSERT INTO PIGGY_BANKS (ID, NAME, TARGET_AMOUNT, CATEGORY, USER_ID, GROUP_ID, TYPE) VALUES (2, 'testgrouppiggy', 2000.00, 'ENTERTAINMENT', NULL, 1, 'GROUP');
ALTER SEQUENCE piggy_bank_seq RESTART WITH 3;

INSERT INTO INVITATIONS (GROUP_ID, INVITEE_ID, STATUS, CREATED_AT) VALUES (1, 2, 'PENDING', CURRENT_DATE);

INSERT INTO PIGGY_BANK_ALLOCATIONS (ID, AMOUNT, DATE, PIGGY_BANK_ID, USER_ID) VALUES (1, 250.00, CURRENT_DATE, 1, 1);
ALTER SEQUENCE allocation_seq RESTART WITH 2;
