events {}

http {
    upstream identity-upstream  { server identity-service:8080; }
    upstream piggybank-upstream { server piggybank-service:8080; }
    upstream budget-upstream    { server budget-service:8080; }

    server {
        listen 80;

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        location /api/v1/users        { proxy_pass http://identity-upstream;  }

        location /api/v1/groups       { proxy_pass http://piggybank-upstream; }
        location /api/v1/invitations  { proxy_pass http://piggybank-upstream; }
        location /api/v1/piggy-banks  { proxy_pass http://piggybank-upstream; }

        location /api/v1/incomes            { proxy_pass http://budget-upstream; }
        location /api/v1/expenses           { proxy_pass http://budget-upstream; }
        location /api/v1/recurring-incomes  { proxy_pass http://budget-upstream; }
        location /api/v1/recurring-expenses { proxy_pass http://budget-upstream; }
        location /api/v1/savings            { proxy_pass http://budget-upstream; }
        location /api/v1/balance            { proxy_pass http://budget-upstream; }
    }
}
