DELETE FROM INVITATIONS;
DELETE FROM PIGGY_BANK_ALLOCATIONS;
DELETE FROM PIGGY_BANKS;
DELETE FROM USER_GROUPS;
DELETE FROM GROUPS;
DELETE FROM USERS;

INSERT INTO USERS (ID) VALUES (1);
INSERT INTO USERS (ID) VALUES (2);
INSERT INTO USERS (ID) VALUES (3);
INSERT INTO USERS (ID) VALUES (4);

INSERT INTO GROUPS (ID, NAME, ADMIN_ID) VALUES (1, 'testgroup', 1);
ALTER SEQUENCE group_seq RESTART WITH 3;

INSERT INTO USER_GROUPS (USER_ID, GROUP_ID) VALUES (1, 1);
INSERT INTO USER_GROUPS (USER_ID, GROUP_ID) VALUES (3, 1);

INSERT INTO PIGGY_BANKS (ID, NAME, TARGET_AMOUNT, CATEGORY, USER_ID, GROUP_ID, TYPE) VALUES (1, 'testpersonalpiggy', 1000.00, 'ENTERTAINMENT', 1, NULL, 'PERSONAL');
INSERT INTO PIGGY_BANKS (ID, NAME, TARGET_AMOUNT, CATEGORY, USER_ID, GROUP_ID, TYPE) VALUES (2, 'testgrouppiggy', 2000.00, 'ENTERTAINMENT', NULL, 1, 'GROUP');
ALTER SEQUENCE piggy_bank_seq RESTART WITH 3;

INSERT INTO INVITATIONS (GROUP_ID, INVITEE_ID, STATUS, CREATED_AT) VALUES (1, 2, 'PENDING', CURRENT_DATE);

INSERT INTO PIGGY_BANK_ALLOCATIONS (ID, AMOUNT, DATE, PIGGY_BANK_ID, USER_ID) VALUES (1, 250.00, CURRENT_DATE, 1, 1);
ALTER SEQUENCE allocation_seq RESTART WITH 2;
