DELETE FROM SAVINGS_OPERATIONS;
DELETE FROM SAVINGS;
DELETE FROM EXPENSES;
DELETE FROM RECURRING_EXPENSES;
DELETE FROM INCOMES;
DELETE FROM RECURRING_INCOMES;
DELETE FROM USERS;

INSERT INTO USERS (ID) VALUES (1);
INSERT INTO USERS (ID) VALUES (2);
INSERT INTO USERS (ID) VALUES (3);
INSERT INTO USERS (ID) VALUES (4);

INSERT INTO SAVINGS (ID, USER_ID) VALUES (1, 1);
INSERT INTO SAVINGS (ID, USER_ID) VALUES (2, 2);
ALTER SEQUENCE savings_seq RESTART WITH 3;
