name: budget-service

on:
  push:
    branches: [main]
    paths:
      - services/budget-service/src/**
      - services/budget-service/pom.xml
      - services/pom.xml
      - Dockerfile
      - .github/workflows/budget-service.yml
      - .github/workflows/service-workflow.yml
  pull_request:
    branches: [main]
    paths:
      - services/budget-service/src/**
      - services/budget-service/pom.xml
      - services/pom.xml
      - Dockerfile
      - .github/workflows/budget-service.yml
      - .github/workflows/service-workflow.yml

jobs:
  run:
    uses: ./.github/workflows/service-workflow.yml
    with:
      service: budget-service
    secrets: inherit
